<?php

/******************************************************************************/
/******************************************************************************/

class CPBSCountry
{
	/**************************************************************************/

	function __construct()
	{
		$this->country=CPBSGlobalData::setGlobalData('country',array($this,'init'));
	}
	
	/**************************************************************************/

	function init()
	{
		$country=array
		(
			'AF'=>array(esc_html__('Afghanistan','car-park-booking-system')),
			'AX'=>array(esc_html__('Aland Islands','car-park-booking-system')),
			'AL'=>array(esc_html__('Albania','car-park-booking-system')),
			'DZ'=>array(esc_html__('Algeria','car-park-booking-system')),
			'AS'=>array(esc_html__('American Samoa','car-park-booking-system')),
			'AD'=>array(esc_html__('Andorra','car-park-booking-system')),
			'AO'=>array(esc_html__('Angola','car-park-booking-system')),
			'AI'=>array(esc_html__('Anguilla','car-park-booking-system')),
			'AQ'=>array(esc_html__('Antarctica','car-park-booking-system')),
			'AG'=>array(esc_html__('Antigua And Barbuda','car-park-booking-system')),
			'AR'=>array(esc_html__('Argentina','car-park-booking-system')),
			'AM'=>array(esc_html__('Armenia','car-park-booking-system')),
			'AW'=>array(esc_html__('Aruba','car-park-booking-system')),
			'AU'=>array(esc_html__('Australia','car-park-booking-system')),
			'AT'=>array(esc_html__('Austria','car-park-booking-system')),
			'AZ'=>array(esc_html__('Azerbaijan','car-park-booking-system')),
			'BS'=>array(esc_html__('Bahamas','car-park-booking-system')),
			'BH'=>array(esc_html__('Bahrain','car-park-booking-system')),
			'BD'=>array(esc_html__('Bangladesh','car-park-booking-system')),
			'BB'=>array(esc_html__('Barbados','car-park-booking-system')),
			'BY'=>array(esc_html__('Belarus','car-park-booking-system')),
			'BE'=>array(esc_html__('Belgium','car-park-booking-system')),
			'BZ'=>array(esc_html__('Belize','car-park-booking-system')),
			'BJ'=>array(esc_html__('Benin','car-park-booking-system')),
			'BM'=>array(esc_html__('Bermuda','car-park-booking-system')),
			'BT'=>array(esc_html__('Bhutan','car-park-booking-system')),
			'BO'=>array(esc_html__('Bolivia','car-park-booking-system')),
			'BA'=>array(esc_html__('Bosnia And Herzegovina','car-park-booking-system')),
			'BW'=>array(esc_html__('Botswana','car-park-booking-system')),
			'BV'=>array(esc_html__('Bouvet Island','car-park-booking-system')),
			'BR'=>array(esc_html__('Brazil','car-park-booking-system')),
			'IO'=>array(esc_html__('British Indian Ocean Territory','car-park-booking-system')),
			'BN'=>array(esc_html__('Brunei Darussalam','car-park-booking-system')),
			'BG'=>array(esc_html__('Bulgaria','car-park-booking-system')),
			'BF'=>array(esc_html__('Burkina Faso','car-park-booking-system')),
			'BI'=>array(esc_html__('Burundi','car-park-booking-system')),
			'KH'=>array(esc_html__('Cambodia','car-park-booking-system')),
			'CM'=>array(esc_html__('Cameroon','car-park-booking-system')),
			'CA'=>array(esc_html__('Canada','car-park-booking-system')),
			'CV'=>array(esc_html__('Cape Verde','car-park-booking-system')),
			'KY'=>array(esc_html__('Cayman Islands','car-park-booking-system')),
			'CF'=>array(esc_html__('Central African Republic','car-park-booking-system')),
			'TD'=>array(esc_html__('Chad','car-park-booking-system')),
			'CL'=>array(esc_html__('Chile','car-park-booking-system')),
			'CN'=>array(esc_html__('China','car-park-booking-system')),
			'CX'=>array(esc_html__('Christmas Island','car-park-booking-system')),
			'CC'=>array(esc_html__('Cocos (Keeling) Islands','car-park-booking-system')),
			'CO'=>array(esc_html__('Colombia','car-park-booking-system')),
			'KM'=>array(esc_html__('Comoros','car-park-booking-system')),
			'CG'=>array(esc_html__('Congo','car-park-booking-system')),
			'CD'=>array(esc_html__('Congo, Democratic Republic','car-park-booking-system')),
			'CK'=>array(esc_html__('Cook Islands','car-park-booking-system')),
			'CR'=>array(esc_html__('Costa Rica','car-park-booking-system')),
			'CI'=>array(esc_html__('Cote D\'Ivoire','car-park-booking-system')),
			'HR'=>array(esc_html__('Croatia','car-park-booking-system')),
			'CU'=>array(esc_html__('Cuba','car-park-booking-system')),
			'CW'=>array(esc_html__('Curaçao','car-park-booking-system')),
			'CY'=>array(esc_html__('Cyprus','car-park-booking-system')),
			'CZ'=>array(esc_html__('Czech Republic','car-park-booking-system')),
			'DK'=>array(esc_html__('Denmark','car-park-booking-system')),
			'DJ'=>array(esc_html__('Djibouti','car-park-booking-system')),
			'DM'=>array(esc_html__('Dominica','car-park-booking-system')),
			'DO'=>array(esc_html__('Dominican Republic','car-park-booking-system')),
			'EC'=>array(esc_html__('Ecuador','car-park-booking-system')),
			'EG'=>array(esc_html__('Egypt','car-park-booking-system')),
			'SV'=>array(esc_html__('El Salvador','car-park-booking-system')),
			'GQ'=>array(esc_html__('Equatorial Guinea','car-park-booking-system')),
			'ER'=>array(esc_html__('Eritrea','car-park-booking-system')),
			'EE'=>array(esc_html__('Estonia','car-park-booking-system')),
			'ET'=>array(esc_html__('Ethiopia','car-park-booking-system')),
			'FK'=>array(esc_html__('Falkland Islands (Malvinas)','car-park-booking-system')),
			'FO'=>array(esc_html__('Faroe Islands','car-park-booking-system')),
			'FJ'=>array(esc_html__('Fiji','car-park-booking-system')),
			'FI'=>array(esc_html__('Finland','car-park-booking-system')),
			'FR'=>array(esc_html__('France','car-park-booking-system')),
			'GF'=>array(esc_html__('French Guiana','car-park-booking-system')),
			'PF'=>array(esc_html__('French Polynesia','car-park-booking-system')),
			'TF'=>array(esc_html__('French Southern Territories','car-park-booking-system')),
			'GA'=>array(esc_html__('Gabon','car-park-booking-system')),
			'GM'=>array(esc_html__('Gambia','car-park-booking-system')),
			'GE'=>array(esc_html__('Georgia','car-park-booking-system')),
			'DE'=>array(esc_html__('Germany','car-park-booking-system')),
			'GH'=>array(esc_html__('Ghana','car-park-booking-system')),
			'GI'=>array(esc_html__('Gibraltar','car-park-booking-system')),
			'GR'=>array(esc_html__('Greece','car-park-booking-system')),
			'GL'=>array(esc_html__('Greenland','car-park-booking-system')),
			'GD'=>array(esc_html__('Grenada','car-park-booking-system')),
			'GP'=>array(esc_html__('Guadeloupe','car-park-booking-system')),
			'GU'=>array(esc_html__('Guam','car-park-booking-system')),
			'GT'=>array(esc_html__('Guatemala','car-park-booking-system')),
			'GG'=>array(esc_html__('Guernsey','car-park-booking-system')),
			'GN'=>array(esc_html__('Guinea','car-park-booking-system')),
			'GW'=>array(esc_html__('Guinea-Bissau','car-park-booking-system')),
			'GY'=>array(esc_html__('Guyana','car-park-booking-system')),
			'HT'=>array(esc_html__('Haiti','car-park-booking-system')),
			'HM'=>array(esc_html__('Heard Island & Mcdonald Islands','car-park-booking-system')),
			'VA'=>array(esc_html__('Holy See (Vatican City State)','car-park-booking-system')),
			'HN'=>array(esc_html__('Honduras','car-park-booking-system')),
			'HK'=>array(esc_html__('Hong Kong','car-park-booking-system')),
			'HU'=>array(esc_html__('Hungary','car-park-booking-system')),
			'IS'=>array(esc_html__('Iceland','car-park-booking-system')),
			'IN'=>array(esc_html__('India','car-park-booking-system')),
			'ID'=>array(esc_html__('Indonesia','car-park-booking-system')),
			'IR'=>array(esc_html__('Iran, Islamic Republic Of','car-park-booking-system')),
			'IQ'=>array(esc_html__('Iraq','car-park-booking-system')),
			'IE'=>array(esc_html__('Ireland','car-park-booking-system')),
			'IM'=>array(esc_html__('Isle Of Man','car-park-booking-system')),
			'IL'=>array(esc_html__('Israel','car-park-booking-system')),
			'IT'=>array(esc_html__('Italy','car-park-booking-system')),
			'JM'=>array(esc_html__('Jamaica','car-park-booking-system')),
			'JP'=>array(esc_html__('Japan','car-park-booking-system')),
			'JE'=>array(esc_html__('Jersey','car-park-booking-system')),
			'JO'=>array(esc_html__('Jordan','car-park-booking-system')),
			'KZ'=>array(esc_html__('Kazakhstan','car-park-booking-system')),
			'KE'=>array(esc_html__('Kenya','car-park-booking-system')),
			'KI'=>array(esc_html__('Kiribati','car-park-booking-system')),
			'KR'=>array(esc_html__('Korea','car-park-booking-system')),
			'KW'=>array(esc_html__('Kuwait','car-park-booking-system')),
			'KG'=>array(esc_html__('Kyrgyzstan','car-park-booking-system')),
			'LA'=>array(esc_html__('Lao People\'s Democratic Republic','car-park-booking-system')),
			'LV'=>array(esc_html__('Latvia','car-park-booking-system')),
			'LB'=>array(esc_html__('Lebanon','car-park-booking-system')),
			'LS'=>array(esc_html__('Lesotho','car-park-booking-system')),
			'LR'=>array(esc_html__('Liberia','car-park-booking-system')),
			'LY'=>array(esc_html__('Libyan Arab Jamahiriya','car-park-booking-system')),
			'LI'=>array(esc_html__('Liechtenstein','car-park-booking-system')),
			'LT'=>array(esc_html__('Lithuania','car-park-booking-system')),
			'LU'=>array(esc_html__('Luxembourg','car-park-booking-system')),
			'MO'=>array(esc_html__('Macao','car-park-booking-system')),
			'MK'=>array(esc_html__('Macedonia','car-park-booking-system')),
			'MG'=>array(esc_html__('Madagascar','car-park-booking-system')),
			'MW'=>array(esc_html__('Malawi','car-park-booking-system')),
			'MY'=>array(esc_html__('Malaysia','car-park-booking-system')),
			'MV'=>array(esc_html__('Maldives','car-park-booking-system')),
			'ML'=>array(esc_html__('Mali','car-park-booking-system')),
			'MT'=>array(esc_html__('Malta','car-park-booking-system')),
			'MH'=>array(esc_html__('Marshall Islands','car-park-booking-system')),
			'MQ'=>array(esc_html__('Martinique','car-park-booking-system')),
			'MR'=>array(esc_html__('Mauritania','car-park-booking-system')),
			'MU'=>array(esc_html__('Mauritius','car-park-booking-system')),
			'YT'=>array(esc_html__('Mayotte','car-park-booking-system')),
			'MX'=>array(esc_html__('Mexico','car-park-booking-system')),
			'FM'=>array(esc_html__('Micronesia, Federated States Of','car-park-booking-system')),
			'MD'=>array(esc_html__('Moldova','car-park-booking-system')),
			'MC'=>array(esc_html__('Monaco','car-park-booking-system')),
			'MN'=>array(esc_html__('Mongolia','car-park-booking-system')),
			'ME'=>array(esc_html__('Montenegro','car-park-booking-system')),
			'MS'=>array(esc_html__('Montserrat','car-park-booking-system')),
			'MA'=>array(esc_html__('Morocco','car-park-booking-system')),
			'MZ'=>array(esc_html__('Mozambique','car-park-booking-system')),
			'MM'=>array(esc_html__('Myanmar','car-park-booking-system')),
			'NA'=>array(esc_html__('Namibia','car-park-booking-system')),
			'NR'=>array(esc_html__('Nauru','car-park-booking-system')),
			'NP'=>array(esc_html__('Nepal','car-park-booking-system')),
			'NL'=>array(esc_html__('Netherlands','car-park-booking-system')),
			'NC'=>array(esc_html__('New Caledonia','car-park-booking-system')),
			'NZ'=>array(esc_html__('New Zealand','car-park-booking-system')),
			'NI'=>array(esc_html__('Nicaragua','car-park-booking-system')),
			'NE'=>array(esc_html__('Niger','car-park-booking-system')),
			'NG'=>array(esc_html__('Nigeria','car-park-booking-system')),
			'NU'=>array(esc_html__('Niue','car-park-booking-system')),
			'NF'=>array(esc_html__('Norfolk Island','car-park-booking-system')),
			'MP'=>array(esc_html__('Northern Mariana Islands','car-park-booking-system')),
			'NO'=>array(esc_html__('Norway','car-park-booking-system')),
			'OM'=>array(esc_html__('Oman','car-park-booking-system')),
			'PK'=>array(esc_html__('Pakistan','car-park-booking-system')),
			'PW'=>array(esc_html__('Palau','car-park-booking-system')),
			'PS'=>array(esc_html__('Palestinian Territory, Occupied','car-park-booking-system')),
			'PA'=>array(esc_html__('Panama','car-park-booking-system')),
			'PG'=>array(esc_html__('Papua New Guinea','car-park-booking-system')),
			'PY'=>array(esc_html__('Paraguay','car-park-booking-system')),
			'PE'=>array(esc_html__('Peru','car-park-booking-system')),
			'PH'=>array(esc_html__('Philippines','car-park-booking-system')),
			'PN'=>array(esc_html__('Pitcairn','car-park-booking-system')),
			'PL'=>array(esc_html__('Poland','car-park-booking-system')),
			'PT'=>array(esc_html__('Portugal','car-park-booking-system')),
			'PR'=>array(esc_html__('Puerto Rico','car-park-booking-system')),
			'QA'=>array(esc_html__('Qatar','car-park-booking-system')),
			'RE'=>array(esc_html__('Reunion','car-park-booking-system')),
			'RO'=>array(esc_html__('Romania','car-park-booking-system')),
			'RU'=>array(esc_html__('Russian Federation','car-park-booking-system')),
			'RW'=>array(esc_html__('Rwanda','car-park-booking-system')),
			'BL'=>array(esc_html__('Saint Barthelemy','car-park-booking-system')),
			'SH'=>array(esc_html__('Saint Helena','car-park-booking-system')),
			'KN'=>array(esc_html__('Saint Kitts And Nevis','car-park-booking-system')),
			'LC'=>array(esc_html__('Saint Lucia','car-park-booking-system')),
			'MF'=>array(esc_html__('Saint Martin','car-park-booking-system')),
			'PM'=>array(esc_html__('Saint Pierre And Miquelon','car-park-booking-system')),
			'VC'=>array(esc_html__('Saint Vincent And Grenadines','car-park-booking-system')),
			'WS'=>array(esc_html__('Samoa','car-park-booking-system')),
			'SM'=>array(esc_html__('San Marino','car-park-booking-system')),
			'ST'=>array(esc_html__('Sao Tome And Principe','car-park-booking-system')),
			'SA'=>array(esc_html__('Saudi Arabia','car-park-booking-system')),
			'SN'=>array(esc_html__('Senegal','car-park-booking-system')),
			'RS'=>array(esc_html__('Serbia','car-park-booking-system')),
			'SC'=>array(esc_html__('Seychelles','car-park-booking-system')),
			'SL'=>array(esc_html__('Sierra Leone','car-park-booking-system')),
			'SG'=>array(esc_html__('Singapore','car-park-booking-system')),
			'SK'=>array(esc_html__('Slovakia','car-park-booking-system')),
			'SI'=>array(esc_html__('Slovenia','car-park-booking-system')),
			'SB'=>array(esc_html__('Solomon Islands','car-park-booking-system')),
			'SO'=>array(esc_html__('Somalia','car-park-booking-system')),
			'ZA'=>array(esc_html__('South Africa','car-park-booking-system')),
			'GS'=>array(esc_html__('South Georgia And Sandwich Isl.','car-park-booking-system')),
			'ES'=>array(esc_html__('Spain','car-park-booking-system')),
			'LK'=>array(esc_html__('Sri Lanka','car-park-booking-system')),
			'SD'=>array(esc_html__('Sudan','car-park-booking-system')),
			'SR'=>array(esc_html__('Suriname','car-park-booking-system')),
			'SJ'=>array(esc_html__('Svalbard And Jan Mayen','car-park-booking-system')),
			'SZ'=>array(esc_html__('Swaziland','car-park-booking-system')),
			'SE'=>array(esc_html__('Sweden','car-park-booking-system')),
			'CH'=>array(esc_html__('Switzerland','car-park-booking-system')),
			'SY'=>array(esc_html__('Syrian Arab Republic','car-park-booking-system')),
			'TW'=>array(esc_html__('Taiwan','car-park-booking-system')),
			'TJ'=>array(esc_html__('Tajikistan','car-park-booking-system')),
			'TZ'=>array(esc_html__('Tanzania','car-park-booking-system')),
			'TH'=>array(esc_html__('Thailand','car-park-booking-system')),
			'TL'=>array(esc_html__('Timor-Leste','car-park-booking-system')),
			'TG'=>array(esc_html__('Togo','car-park-booking-system')),
			'TK'=>array(esc_html__('Tokelau','car-park-booking-system')),
			'TO'=>array(esc_html__('Tonga','car-park-booking-system')),
			'TT'=>array(esc_html__('Trinidad And Tobago','car-park-booking-system')),
			'TN'=>array(esc_html__('Tunisia','car-park-booking-system')),
			'TR'=>array(esc_html__('Turkey','car-park-booking-system')),
			'TM'=>array(esc_html__('Turkmenistan','car-park-booking-system')),
			'TC'=>array(esc_html__('Turks And Caicos Islands','car-park-booking-system')),
			'TV'=>array(esc_html__('Tuvalu','car-park-booking-system')),
			'UG'=>array(esc_html__('Uganda','car-park-booking-system')),
			'UA'=>array(esc_html__('Ukraine','car-park-booking-system')),
			'AE'=>array(esc_html__('United Arab Emirates','car-park-booking-system')),
			'GB'=>array(esc_html__('United Kingdom','car-park-booking-system')),
			'US'=>array(esc_html__('United States','car-park-booking-system')),
			'UM'=>array(esc_html__('United States Outlying Islands','car-park-booking-system')),
			'UY'=>array(esc_html__('Uruguay','car-park-booking-system')),
			'UZ'=>array(esc_html__('Uzbekistan','car-park-booking-system')),
			'VU'=>array(esc_html__('Vanuatu','car-park-booking-system')),
			'VE'=>array(esc_html__('Venezuela','car-park-booking-system')),
			'VN'=>array(esc_html__('Viet Nam','car-park-booking-system')),
			'VG'=>array(esc_html__('Virgin Islands, British','car-park-booking-system')),
			'VI'=>array(esc_html__('Virgin Islands, U.S.','car-park-booking-system')),
			'WF'=>array(esc_html__('Wallis And Futuna','car-park-booking-system')),
			'EH'=>array(esc_html__('Western Sahara','car-park-booking-system')),
			'YE'=>array(esc_html__('Yemen','car-park-booking-system')),
			'ZM'=>array(esc_html__('Zambia','car-park-booking-system')),
			'ZW'=>array(esc_html__('Zimbabwe','car-park-booking-system'))
		);	
		
		return($country);
	}
	
	/**************************************************************************/
	
	function getCountry($country=null)
	{
		if(is_null($country)) return($this->country);
		else return($this->country[$country]);
	}
	
	/**************************************************************************/
	
	function isCountry($index)
	{
		return(array_key_exists($index,$this->country));
	}
	
	/**************************************************************************/
	
	function getCountryName($index)
	{
		return($this->country[$index][0]);
	}
	
	/**************************************************************************/
}

/******************************************************************************/
/******************************************************************************/